(function(){'use strict';
var e,f="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},g="object"===typeof f.global&&f.global?f.global:"object"===typeof global&&global&&global.Object===Object?global:this;f.global=g;var l=exports;f.exportsNamespace=l;g.Object.freeze(f);var aa={envInfo:f,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.15"};g.Object.freeze(aa);g.Object.freeze(aa.semantics);
var q=g.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ba=g.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},ca=0,da=g.WeakMap?new g.WeakMap:null;function t(a){return function(b,c){return!(!b||!b.a||b.a.D!==c||b.a.B!==a)}}function ea(a){for(var b in a)return b}
function fa(a,b,c){var d=new a.sa(b[c]);if(c<b.length-1){a=a.G;c+=1;for(var h=d.la,k=0;k<h.length;k++)h[k]=fa(a,b,c)}return d}function ga(a){return void 0===a?"undefined":a.toString()}
function ha(a){switch(typeof a){case "string":return u(ia);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?u(ja):b<<16>>16===b&&1/b!==1/-0?u(ka):u(la):"number"===typeof a?u(ma):u(na);case "boolean":return u(oa);case "undefined":return u(pa);default:return null===a?a.Cc():qa(a)?u(ra):a&&a.a?u(a.a):null}}
function sa(a){switch(typeof a){case "string":return ta(v(),a);case "number":return ua(va(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.p():null===da?42:wa(a)}}function xa(a,b){var c=g.Object.getPrototypeOf,d=g.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var h=d(a,b);if(void 0!==h)return h;a=c(a)}}function ya(a,b,c){a=xa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function za(a,b,c,d){a=xa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new g.TypeError("super has no setter '"+c+"'.");}
var wa=null!==da?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return sa(a);default:if(null===a)return 0;var b=da.get(a);void 0===b&&(ca=b=ca+1|0,da.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(g.Object.isSealed(a))return 42;ca=b=ca+1|0;return a.$idHashCode$0=b}return null===a?0:sa(a)};
function w(){this.V=this.sa=void 0;this.B=this.G=this.j=null;this.D=0;this.na=null;this.R="";this.h=this.O=this.P=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function x(a,b,c){var d=new w;d.j={};d.G=null;d.na=a;d.R=b;d.h=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function y(a,b,c,d,h,k,n){var p=new w,C=ea(a);k=k||function(a){return!!(a&&a.a&&a.a.j[C])};n=n||function(a,b){return!!(a&&a.a&&a.a.D===b&&a.a.B.j[C])};p.V=h;p.j=c;p.R="L"+b+";";p.h=n;p.name=b;p.isInterface=!1;p.isRawJSType=!!d;p.isInstance=k;return p}
function Aa(a){function b(a){if("number"===typeof a){this.la=Array(a);for(var b=0;b<a;b++)this.la[b]=h}else this.la=a}var c=new w,d=a.na,h="longZero"==d?z().N:d;b.prototype=new A;b.prototype.constructor=b;b.prototype.a=c;var d="["+a.R,k=a.B||a,n=a.D+1;c.sa=b;c.V=Ba;c.j={c:1,Ca:1,d:1};c.G=a;c.B=k;c.D=n;c.na=null;c.R=d;c.P=void 0;c.O=void 0;c.h=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return k.h(a,n)};return c}
function u(a){if(!a.P){var b=new B;b.r=a;a.P=b}return a.P}w.prototype.getFakeInstance=function(){return this===ia?"some string":this===oa?!1:this===ja||this===ka||this===la||this===ma||this===na?0:this===ra?z().N:this===pa?void 0:{a:this}};w.prototype.getSuperclass=function(){return this.V?u(this.V):null};w.prototype.getComponentType=function(){return this.G?u(this.G):null};w.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.O||(b.O=Aa(b)),b=b.O;return fa(b,a,0)};
var Ca=x(!1,"Z","boolean"),Da=x(0,"C","char"),Ea=x(0,"B","byte"),Fa=x(0,"S","short"),Ga=x(0,"I","int"),Ha=x("longZero","J","long"),Ia=x(0,"F","float"),Ja=x(0,"D","double");Ca.h=t(Ca);Da.h=t(Da);Ea.h=t(Ea);Fa.h=t(Fa);Ga.h=t(Ga);Ha.h=t(Ha);Ia.h=t(Ia);Ja.h=t(Ja);var Ka=require("./classes/jsexamplemodule");function D(){}function A(){}A.prototype=D.prototype;D.prototype.b=function(){return this};D.prototype.f=function(){var a=ha(this).r.name,b=(+(this.p()>>>0)).toString(16);return a+"@"+b};D.prototype.p=function(){return wa(this)};D.prototype.toString=function(){return this.f()};var Ba=y({c:0},"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.a){var c=a.D||0;return!(c<b)&&(c>b||!a.B.isPrimitive)}return!1});
D.prototype.a=Ba;function La(a,b){for(var c=0,d=a.U();c<d;)b.Q(a.$(c)),c=1+c|0}function Ma(a,b,c,d,h){var k=Na();E(b.i,c);a.S(Oa(function(a,b,c){return function(d){if(a.g)Pa(b,d),a.g=!1;else return E(b.i,c),Pa(b,d)}}(k,b,d)));E(b.i,h);return b}function Qa(a,b,c){return a.qa((new F).b(),b,c,")").i.e}function G(){}G.prototype=new A;G.prototype.constructor=G;G.prototype.b=function(){return this};G.prototype.testScalaFunc=function(a){return Ka.testFunc(a)};
G.prototype.a=y({Ra:0},"spike.webapp.js.JsExportModule$",{Ra:1,c:1});var Ra=void 0;function H(){}H.prototype=new A;H.prototype.constructor=H;H.prototype.b=function(){return this};H.prototype.a=y({Ta:0},"spike.webapp.shared.PiCalc$",{Ta:1,c:1});var Sa=void 0;function B(){this.r=null}B.prototype=new A;B.prototype.constructor=B;B.prototype.f=function(){return(this.r.isInterface?"interface ":this.r.isPrimitive?"":"class ")+this.r.name};B.prototype.a=y({eb:0},"java.lang.Class",{eb:1,c:1});
function Ta(){this.ua=this.Fa=null}Ta.prototype=new A;Ta.prototype.constructor=Ta;Ta.prototype.b=function(){Ua=this;this.Fa=Va(!1);this.ua=Va(!0);return this};function Wa(){Xa();var a=z(),b=+(new g.Date).getTime(),b=Ya(a,b);return(new I).q(b,a.M)}Ta.prototype.a=y({pb:0},"java.lang.System$",{pb:1,c:1});var Ua=void 0;function Xa(){Ua||(Ua=(new Ta).b());return Ua}function Za(){this.da=null}Za.prototype=new A;Za.prototype.constructor=Za;
Za.prototype.b=function(){$a=this;this.da=(new J).J(Xa().Fa);(new J).J(Xa().ua);(new J).J(null);return this};Za.prototype.a=y({ub:0},"scala.Console$",{ub:1,c:1});var $a=void 0;function ab(){$a||($a=(new Za).b());return $a}function J(){this.Z=null}J.prototype=new A;J.prototype.constructor=J;J.prototype.f=function(){return"DynamicVariable("+this.Z+")"};J.prototype.J=function(a){this.Z=a;return this};J.prototype.a=y({Bb:0},"scala.util.DynamicVariable",{Bb:1,c:1});function bb(){this.ia=null}
bb.prototype=new A;bb.prototype.constructor=bb;function cb(){}cb.prototype=bb.prototype;bb.prototype.$a=function(a){this.ia=a;return this};function db(){}db.prototype=new A;db.prototype.constructor=db;function eb(){}eb.prototype=db.prototype;function fb(a,b){b=q(-862048943,b);b=q(461845907,b<<15|b>>>17|0);a^=b;return-430675100+q(5,a<<13|a>>>19|0)|0}function gb(a){a=q(-2048144789,a^(a>>>16|0));a=q(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function hb(a){ib();for(var b=-889275714,c=0;1>c;)b=fb(b,jb(kb(),a.ea(c))),c=1+c|0;return gb(b^1)}function lb(a,b,c){var d=(new L).I(0);c=(new L).I(c);b.S(Oa(function(a,b,c){return function(a){c.g=fb(c.g,jb(kb(),a));b.g=1+b.g|0}}(a,d,c)));return gb(c.g^d.g)}function mb(){this.ta=null}mb.prototype=new A;mb.prototype.constructor=mb;mb.prototype.b=function(){nb=this;this.ta=(new M).b();return this};mb.prototype.a=y({Tb:0},"scala.collection.Iterator$",{Tb:1,c:1});var nb=void 0;
function ob(){this.v=!1;this.xa=this.T=this.C=null;this.aa=!1;this.Ea=this.za=0}ob.prototype=new A;ob.prototype.constructor=ob;
ob.prototype.b=function(){pb=this;this.C=(this.v=!!(g.ArrayBuffer&&g.Int32Array&&g.Float32Array&&g.Float64Array))?new g.ArrayBuffer(8):null;this.T=this.v?new g.Int32Array(this.C,0,2):null;this.v&&new g.Float32Array(this.C,0,2);this.xa=this.v?new g.Float64Array(this.C,0,1):null;if(this.v)this.T[0]=16909060,a=1===((new g.Int8Array(this.C,0,8))[0]|0);else var a=!0;this.za=(this.aa=a)?0:1;this.Ea=this.aa?1:0;return this};
function ua(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.v)a.xa[0]=b,a=(new I).q(a.T[a.Ea]|0,a.T[a.za]|0);else{if(b!==b)a=!1,b=2047,c=+g.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+g.Math.pow(2,-1022)){b=+g.Math.pow(2,52);var c=+g.Math.log(d)/.6931471805599453,c=+g.Math.floor(c)|0,c=1023>c?c:1023,h=d/+g.Math.pow(2,c)*b,d=+g.Math.floor(h),h=h-d,d=.5>h?d:.5<h?1+d:0!==d%2?1+d:d;2<=d/b&&(c=1+c|0,d=1);
1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+g.Math.pow(2,-1074),c=+g.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new I).q(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.o^a.n}ob.prototype.a=y({qc:0},"scala.scalajs.runtime.Bits$",{qc:1,c:1});var pb=void 0;function va(){pb||(pb=(new ob).b());return pb}function qb(){}qb.prototype=new A;qb.prototype.constructor=qb;qb.prototype.b=function(){return this};
function rb(a){if(0===(-65536&a))return g.String.fromCharCode(a);if(0>a||1114111<a)throw(new N).b();a=-65536+a|0;return g.String.fromCharCode(55296|a>>10,56320|1023&a)}function ta(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+q(65535&(b.charCodeAt(d)|0),c)|0,c=q(31,c),d=-1+d|0;return a}qb.prototype.a=y({sc:0},"scala.scalajs.runtime.RuntimeString$",{sc:1,c:1});var sb=void 0;function v(){sb||(sb=(new qb).b());return sb}function O(){}O.prototype=new A;O.prototype.constructor=O;O.prototype.b=function(){return this};
O.prototype.a=y({tc:0},"scala.scalajs.runtime.package$",{tc:1,c:1});var tb=void 0;function ub(){}ub.prototype=new A;ub.prototype.constructor=ub;ub.prototype.b=function(){return this};
function jb(a,b){if(null===b)return 0;if(b&&b.a&&b.a.j.t||"number"===typeof b){if("number"===typeof b){a=+b;vb||(vb=(new P).b());b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var c=z();b=Ya(c,a);c=c.M;z();a=(0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0))===a?b^c:ua(va(),a)}return a}if(qa(b))return b=null===b?z().N:b,a=b.o,b=b.n,vb||(vb=(new P).b()),b=(new I).q(a,b),a=b.o,b=b.n,b===a>>31?a:a^b}return sa(b)}
ub.prototype.a=y({xc:0},"scala.runtime.ScalaRunTime$",{xc:1,c:1});var wb=void 0;function kb(){wb||(wb=(new ub).b());return wb}function P(){}P.prototype=new A;P.prototype.constructor=P;P.prototype.b=function(){return this};P.prototype.a=y({zc:0},"scala.runtime.Statics$",{zc:1,c:1});var vb=void 0;function Q(){}Q.prototype=new A;Q.prototype.constructor=Q;Q.prototype.b=function(){return this};
Q.prototype.main=function(){var a=new xb,b=yb(["Pi approximation for "," iterations : ",""]);a.W=b;var c=Wa(),b=c.o,c=c.n,d;Sa||(Sa=(new H).b());for(var h=d=0;;){var k=zb(),n=zb();1>=k*k+n*n&&(d=1+d|0);if(1E6===h)break;h=1+h|0}d=d/1E6*4;k=Wa();h=k.o;k=k.n;b=h-b|0;b="Elapsed time: "+(new I).q(b,(-2147483648^b)>(-2147483648^h)?-1+(k-c|0)|0:k-c|0)+"ms";Ab(ab().da.Z,b+"\n");a=Bb(a,yb([1E6,d]));Ab(ab().da.Z,a+"\n")};Q.prototype.a=y({Sa:0},"spike.webapp.js.SpikeApp$",{Sa:1,c:1,Tc:1});var Cb=void 0;
function Db(){}Db.prototype=new A;Db.prototype.constructor=Db;function Eb(){}Eb.prototype=Db.prototype;function R(){this.m=null}R.prototype=new A;R.prototype.constructor=R;function Fb(){}Fb.prototype=R.prototype;
R.prototype.wa=function(){if(void 0===g.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(tb||(tb=(new O).b()),(a=b&&b.a&&b.a.j.y?b:(new Gb).J(b))&&a.a&&a.a.j.ka)a=a.w;else throw tb||(tb=(new O).b()),a&&a.a&&a.a.j.ka?a.w:a;}this.stackdata=a}else g.Error.captureStackTrace(this),this.stackdata=this;return this};R.prototype.ya=function(){return this.m};R.prototype.f=function(){var a=ha(this).r.name,b=this.ya();return null===b?a:a+": "+b};R.prototype.s=function(a){this.m=a;this.wa();return this};
function S(){this.ha=this.ga=0}S.prototype=new A;S.prototype.constructor=S;S.prototype.b=function(){S.prototype.Wa.call(this,Hb());return this};S.prototype.Wa=function(a){var b=-554899859^a.o;this.ga=b>>>24|0|(65535&(5^a.n))<<8;this.ha=16777215&b;return this};function Ib(a,b){var c=a.ha,d=11+15525485*c,c=16777215&((d/16777216|0)+(16777215&(1502*c+15525485*a.ga|0))|0),d=16777215&(d|0);a.ga=c;a.ha=d;return(c<<8|d>>16)>>>(32-b|0)|0}
function zb(){Jb||(Jb=(new Kb).b());var a=Jb.ia;return(134217728*Ib(a,26)+Ib(a,27))/9007199254740992}S.prototype.a=y({rb:0},"java.util.Random",{rb:1,c:1,d:1});function Kb(){this.ia=null}Kb.prototype=new cb;Kb.prototype.constructor=Kb;Kb.prototype.b=function(){bb.prototype.$a.call(this,(new S).b());return this};Kb.prototype.a=y({Cb:0},"scala.util.Random$",{Cb:1,Gc:1,c:1});var Jb=void 0;function Lb(){this.ja=0}Lb.prototype=new eb;Lb.prototype.constructor=Lb;
Lb.prototype.b=function(){Mb=this;this.ja=ta(v(),"Seq");ta(v(),"Map");ta(v(),"Set");return this};function Nb(a){var b=ib(),c;if(a&&a.a&&a.a.j.Mc){c=0;for(var b=b.ja,d=a;!d.Ec();)a=d.Dc(),d=d.Vc(),b=fb(b,jb(kb(),a)),c=1+c|0;c=gb(b^c)}else c=lb(b,a,b.ja);return c}Lb.prototype.a=y({Db:0},"scala.util.hashing.MurmurHash3$",{Db:1,Hc:1,c:1});var Mb=void 0;function ib(){Mb||(Mb=(new Lb).b());return Mb}function Ob(){}Ob.prototype=new A;Ob.prototype.constructor=Ob;function Pb(){}Pb.prototype=Ob.prototype;
Ob.prototype.f=function(){return"\x3cfunction1\x3e"};function Qb(){this.g=!1}Qb.prototype=new A;Qb.prototype.constructor=Qb;Qb.prototype.f=function(){return""+this.g};function Na(){var a=new Qb;a.g=!0;return a}Qb.prototype.a=y({uc:0},"scala.runtime.BooleanRef",{uc:1,c:1,d:1});var pa=y({vc:0},"scala.runtime.BoxedUnit",{vc:1,c:1,d:1},void 0,void 0,function(a){return void 0===a});function L(){this.g=0}L.prototype=new A;L.prototype.constructor=L;L.prototype.f=function(){return""+this.g};
L.prototype.I=function(a){this.g=a;return this};L.prototype.a=y({wc:0},"scala.runtime.IntRef",{wc:1,c:1,d:1});function Rb(){}Rb.prototype=new A;Rb.prototype.constructor=Rb;function Sb(){}Sb.prototype=Rb.prototype;var oa=y({bb:0},"java.lang.Boolean",{bb:1,c:1,d:1,l:1},void 0,void 0,function(a){return"boolean"===typeof a});function T(){this.ma=0}T.prototype=new A;T.prototype.constructor=T;T.prototype.f=function(){return g.String.fromCharCode(this.ma)};function Tb(a){var b=new T;b.ma=a;return b}
T.prototype.p=function(){return this.ma};T.prototype.a=y({db:0},"java.lang.Character",{db:1,c:1,d:1,l:1});function Ub(){this.m=null}Ub.prototype=new Fb;Ub.prototype.constructor=Ub;function Vb(){}Vb.prototype=Ub.prototype;function Wb(){}Wb.prototype=new A;Wb.prototype.constructor=Wb;Wb.prototype.b=function(){return this};function Hb(){Xb||(Xb=(new Wb).b());var a=Yb(),b=Yb();return(new I).q(b,a)}
function Yb(){var a=4294967296*+g.Math.random(),a=-2147483648+ +g.Math.floor(a);return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}Wb.prototype.a=y({sb:0},"java.util.Random$",{sb:1,c:1,z:1,d:1});var Xb=void 0;function Zb(){}Zb.prototype=new A;Zb.prototype.constructor=Zb;Zb.prototype.b=function(){return this};Zb.prototype.a=y({zb:0},"scala.StringContext$",{zb:1,c:1,z:1,d:1});var $b=void 0;function ac(){this.va=null}ac.prototype=new Pb;ac.prototype.constructor=ac;
ac.prototype.Q=function(a){return(0,this.va)(a)};function Oa(a){var b=new ac;b.va=a;return b}ac.prototype.a=y({pc:0},"scala.scalajs.runtime.AnonFunction1",{pc:1,Uc:1,c:1,pa:1});function bc(){this.M=0;this.N=null}bc.prototype=new A;bc.prototype.constructor=bc;bc.prototype.b=function(){cc=this;this.N=(new I).q(0,0);return this};
function dc(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ba(1E9)|0)-(0!==b?ba(b):32+ba(a)|0)|0,d=c,h=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,k=a,n=b;for(a=b=0;0<=c&&0!==(-2097152&n);){var p=k,C=n,yc=h,K=d;if(C===K?(-2147483648^p)>=(-2147483648^yc):(-2147483648^C)>=(-2147483648^K))p=n,C=d,n=k-h|0,p=(-2147483648^n)>(-2147483648^k)?-1+(p-C|0)|0:p-C|0,k=n,n=p,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;p=d>>>1|0;h=h>>>1|0|d<<31;d=p}c=n;if(0===c?-1147483648<=(-2147483648^
k):-2147483648<=(-2147483648^c))c=4294967296*n+ +(k>>>0),k=c/1E9,h=k/4294967296|0,d=b,b=k=d+(k|0)|0,a=(-2147483648^k)<(-2147483648^d)?1+(a+h|0)|0:a+h|0,k=c%1E9|0;c=""+k;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function Ya(a,b){if(-9223372036854775808>b)return a.M=-2147483648,0;if(0x7fffffffffffffff<=b)return a.M=2147483647,-1;var c=b|0,d=b/4294967296|0;a.M=0>b&&0!==c?-1+d|0:d;return c}bc.prototype.a=y({rc:0},"scala.scalajs.runtime.RuntimeLong$",{rc:1,c:1,z:1,d:1});
var cc=void 0;function z(){cc||(cc=(new bc).b());return cc}function ec(){}ec.prototype=new Sb;ec.prototype.constructor=ec;function fc(){}fc.prototype=ec.prototype;ec.prototype.Xa=function(){return this};
var ia=y({Ua:0},"java.lang.String",{Ua:1,c:1,d:1,Ba:1,l:1},void 0,void 0,function(a){return"string"===typeof a}),ja=y({cb:0},"java.lang.Byte",{cb:1,t:1,c:1,d:1,l:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),na=y({fb:0},"java.lang.Double",{fb:1,t:1,c:1,d:1,l:1},void 0,void 0,function(a){return"number"===typeof a}),ma=y({gb:0},"java.lang.Float",{gb:1,t:1,c:1,d:1,l:1},void 0,void 0,function(a){return"number"===typeof a}),la=y({ib:0},"java.lang.Integer",{ib:1,t:1,c:1,d:1,l:1},void 0,
void 0,function(a){return(a|0)===a&&1/a!==1/-0});function gc(){}gc.prototype=new Sb;gc.prototype.constructor=gc;gc.prototype.b=function(){return this};gc.prototype.a=y({kb:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{kb:1,Qa:1,c:1,Oa:1,Pa:1});var ra=y({lb:0},"java.lang.Long",{lb:1,t:1,c:1,d:1,l:1},void 0,void 0,function(a){return qa(a)});function hc(){this.m=null}hc.prototype=new Vb;hc.prototype.constructor=hc;function ic(){}ic.prototype=hc.prototype;
var ka=y({nb:0},"java.lang.Short",{nb:1,t:1,c:1,d:1,l:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function V(){this.e=null}V.prototype=new A;V.prototype.constructor=V;e=V.prototype;e.b=function(){V.prototype.k.call(this,"");return this};function E(a,b){a.e=""+a.e+(null===b?"null":b);return a}e.Ma=function(a,b){return this.e.substring(a,b)};e.f=function(){return this.e};function jc(a,b){null===b?E(a,null):E(a,ga(b))}e.I=function(){V.prototype.k.call(this,"");return this};
function kc(a,b,c,d){null===b?a=kc(a,"null",c,d):(b="string"===typeof b?b.substring(c,d):b.Ma(c,d),a=E(a,ga(b)));return a}function lc(a,b){E(a,g.String.fromCharCode(b))}e.k=function(a){this.e=a;return this};e.a=y({ob:0},"java.lang.StringBuilder",{ob:1,c:1,Ba:1,ab:1,d:1});function W(){}W.prototype=new A;W.prototype.constructor=W;function mc(){}mc.prototype=W.prototype;W.prototype.f=function(){return(this.H()?"non-empty":"empty")+" iterator"};W.prototype.S=function(a){for(;this.H();)a.Q(this.u())};
W.prototype.qa=function(a,b,c,d){return Ma(this,a,b,c,d)};function I(){this.n=this.o=0}I.prototype=new Eb;I.prototype.constructor=I;e=I.prototype;e.f=function(){z();var a=this.o,b=this.n;return b===a>>31?""+a:0>b?"-"+dc(-a|0,0!==a?~b:-b|0):dc(a,b)};e.q=function(a,b){this.o=a;this.n=b;return this};e.I=function(a){I.prototype.q.call(this,a,a>>31);return this};e.p=function(){return this.o^this.n};function qa(a){return!!(a&&a.a&&a.a.j.Ka)}
e.a=y({Ka:0},"scala.scalajs.runtime.RuntimeLong",{Ka:1,t:1,c:1,d:1,l:1});function N(){this.m=null}N.prototype=new ic;N.prototype.constructor=N;function nc(){}nc.prototype=N.prototype;N.prototype.b=function(){R.prototype.s.call(this,null);return this};N.prototype.k=function(a){R.prototype.s.call(this,a);return this};N.prototype.a=y({Da:0},"java.lang.IllegalArgumentException",{Da:1,L:1,K:1,y:1,c:1,d:1});function X(){this.m=null}X.prototype=new ic;X.prototype.constructor=X;
X.prototype.k=function(a){R.prototype.s.call(this,a);return this};X.prototype.a=y({hb:0},"java.lang.IndexOutOfBoundsException",{hb:1,L:1,K:1,y:1,c:1,d:1});function oc(){this.m=null}oc.prototype=new ic;oc.prototype.constructor=oc;oc.prototype.b=function(){R.prototype.s.call(this,null);return this};oc.prototype.a=y({mb:0},"java.lang.NullPointerException",{mb:1,L:1,K:1,y:1,c:1,d:1});function pc(){this.m=null}pc.prototype=new ic;pc.prototype.constructor=pc;
pc.prototype.k=function(a){R.prototype.s.call(this,a);return this};pc.prototype.a=y({qb:0},"java.util.NoSuchElementException",{qb:1,L:1,K:1,y:1,c:1,d:1});function xb(){this.W=null}xb.prototype=new A;xb.prototype.constructor=xb;e=xb.prototype;e.Ha=function(){return"StringContext"};e.ea=function(a){switch(a){case 0:return this.W;default:throw(new X).k(""+a);}};e.f=function(){kb();var a=this.Ga();return Qa(a,this.Ha()+"(",",")};
function Bb(a,b){function c(a){$b||($b=(new Zb).b());var b;b=null;var c;c=0;var d=a.length|0,h;h=0;var K,m;for(m=0;m<d;)if(K=m,92===(65535&(a.charCodeAt(m)|0))){m=1+m|0;if(m>=d)throw qc(a,K);if(48<=(65535&(a.charCodeAt(m)|0))&&55>=(65535&(a.charCodeAt(m)|0))){var r=65535&(a.charCodeAt(m)|0),U=-48+r|0;m=1+m|0;m<d&&48<=(65535&(a.charCodeAt(m)|0))&&55>=(65535&(a.charCodeAt(m)|0))&&(U=-48+((U<<3)+(65535&(a.charCodeAt(m)|0))|0)|0,m=1+m|0,m<d&&51>=r&&48<=(65535&(a.charCodeAt(m)|0))&&55>=(65535&(a.charCodeAt(m)|
0))&&(U=-48+((U<<3)+(65535&(a.charCodeAt(m)|0))|0)|0,m=1+m|0));r=65535&U}else switch(r=65535&(a.charCodeAt(m)|0),m=1+m|0,r){case 98:r=8;break;case 116:r=9;break;case 110:r=10;break;case 102:r=12;break;case 114:r=13;break;case 34:r=34;break;case 39:r=39;break;case 92:r=92;break;default:throw qc(a,K);}0===(1&c)&&0===(1&c)&&(b=(new V).b(),c|=1);U=b;kc(U,a,h,K);0===(1&c)&&0===(1&c)&&(b=(new V).b(),c|=1);h=b;lc(h,r);h=m}else m=1+m|0;0!==h&&(0===(1&c)&&0===(1&c)&&(b=(new V).b()),a=kc(b,a,h,m).e);return a}
if(a.W.U()!==(1+b.U()|0))throw(new N).k("wrong number of arguments for interpolated string");a=a.W.ca();b=b.ca();for(var d=a.u(),d=(new V).k(c(d));b.H();){jc(d,b.u());var h=a.u();E(d,c(h))}return d.e}e.p=function(){return hb(this)};e.Ga=function(){return rc(this)};e.a=y({yb:0},"scala.StringContext",{yb:1,c:1,xb:1,fa:1,z:1,d:1});function M(){}M.prototype=new mc;M.prototype.constructor=M;M.prototype.b=function(){return this};M.prototype.u=function(){throw(new pc).k("next on empty iterator");};
M.prototype.H=function(){return!1};M.prototype.a=y({Ub:0},"scala.collection.Iterator$$anon$2",{Ub:1,Ia:1,c:1,Ja:1,Y:1,X:1});function Y(){this.ra=this.F=0;this.Na=null}Y.prototype=new mc;Y.prototype.constructor=Y;Y.prototype.u=function(){var a=this.Na.ea(this.F);this.F=1+this.F|0;return a};function rc(a){var b=new Y;b.Na=a;b.F=0;b.ra=1;return b}Y.prototype.H=function(){return this.F<this.ra};Y.prototype.a=y({yc:0},"scala.runtime.ScalaRunTime$$anon$1",{yc:1,Ia:1,c:1,Ja:1,Y:1,X:1});function sc(){}
sc.prototype=new fc;sc.prototype.constructor=sc;function tc(){}tc.prototype=sc.prototype;sc.prototype.Ya=function(){ec.prototype.Xa.call(this);return this};function uc(){this.m=null}uc.prototype=new nc;uc.prototype.constructor=uc;function qc(a,b){var c=new uc;R.prototype.s.call(c,"invalid escape character at index "+b+' in "'+a+'"');return c}uc.prototype.a=y({Ab:0},"scala.StringContext$InvalidEscapeException",{Ab:1,Da:1,L:1,K:1,y:1,c:1,d:1});function vc(){this.E=this.Aa=null}vc.prototype=new tc;
vc.prototype.constructor=vc;function Va(a){var b=new vc;b.Aa=a;(new gc).b();sc.prototype.Ya.call(b);b.E="";return b}function Ab(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.E=""+a.E+b,b="";else{var d=""+a.E+b.substring(0,c);g.console&&(a.Aa&&g.console.error?g.console.error(d):g.console.log(d));a.E="";b=b.substring(1+c|0)}}}vc.prototype.a=y({jb:0},"java.lang.JSConsoleBasedPrintStream",{jb:1,Bc:1,Ac:1,Qa:1,c:1,Oa:1,Pa:1,ab:1});function Z(){this.x=this.ba=0;this.oa=null}Z.prototype=new mc;
Z.prototype.constructor=Z;Z.prototype.u=function(){this.x>=this.ba&&(nb||(nb=(new mb).b()),nb.ta.u());var a=this.oa.$(this.x);this.x=1+this.x|0;return a};function wc(a,b){var c=new Z;c.ba=b;if(null===a)throw(new oc).b();c.oa=a;c.x=0;return c}Z.prototype.H=function(){return this.x<this.ba};Z.prototype.a=y({Pb:0},"scala.collection.IndexedSeqLike$Elements",{Pb:1,Ia:1,c:1,Ja:1,Y:1,X:1,Ic:1,z:1,d:1});function Gb(){this.w=this.m=null}Gb.prototype=new ic;Gb.prototype.constructor=Gb;e=Gb.prototype;e.Ha=function(){return"JavaScriptException"};
e.wa=function(){this.stackdata=this.w;return this};e.ea=function(a){switch(a){case 0:return this.w;default:throw(new X).k(""+a);}};e.ya=function(){return ga(this.w)};e.J=function(a){this.w=a;R.prototype.s.call(this,null);return this};e.p=function(){return hb(this)};e.Ga=function(){return rc(this)};e.a=y({ka:0},"scala.scalajs.js.JavaScriptException",{ka:1,L:1,K:1,y:1,c:1,d:1,xb:1,fa:1,z:1});function xc(){}xc.prototype=new A;xc.prototype.constructor=xc;function zc(){}zc.prototype=xc.prototype;
xc.prototype.qa=function(a,b,c,d){return Ma(this,a,b,c,d)};xc.prototype.La=function(){var a=ha(this).r.name,b;v();b=a;var c=rb(46);b=b.lastIndexOf(c)|0;-1!==b&&(a=a.substring(1+b|0));v();b=a;c=rb(36);b=b.indexOf(c)|0;-1!==b&&(a=a.substring(0,b));return a};function Ac(){}Ac.prototype=new zc;Ac.prototype.constructor=Ac;function Bc(){}Bc.prototype=Ac.prototype;function Cc(){}Cc.prototype=new Bc;Cc.prototype.constructor=Cc;function Dc(){}Dc.prototype=Cc.prototype;
Cc.prototype.f=function(){var a=this.La()+"(";return Qa(this,a,", ")};function Ec(){}Ec.prototype=new Dc;Ec.prototype.constructor=Ec;function Fc(){}Fc.prototype=Ec.prototype;function Gc(){}Gc.prototype=new Fc;Gc.prototype.constructor=Gc;function Hc(){}Hc.prototype=Gc.prototype;function F(){this.i=null}F.prototype=new Fc;F.prototype.constructor=F;e=F.prototype;e.b=function(){F.prototype.Va.call(this,16,"");return this};e.$=function(a){a=65535&(this.i.e.charCodeAt(a)|0);return Tb(a)};
e.Q=function(a){a=65535&(this.i.e.charCodeAt(a|0)|0);return Tb(a)};e.Ma=function(a,b){return this.i.e.substring(a,b)};e.f=function(){return this.i.e};e.S=function(a){La(this,a)};e.ca=function(){return wc(this,this.i.e.length|0)};e.Va=function(a,b){F.prototype.Za.call(this,E((new V).I((b.length|0)+a|0),b));return this};e.U=function(){return this.i.e.length|0};e.Za=function(a){this.i=a;return this};function Pa(a,b){var c=a.i;v();E(c,null===b?"null":ga(b));return a}e.p=function(){return Nb(this)};
e.a=y({mc:0},"scala.collection.mutable.StringBuilder",{mc:1,ec:1,Fb:1,Eb:1,Gb:1,c:1,Yb:1,Zb:1,dc:1,ac:1,Y:1,X:1,Mb:1,Vb:1,Lb:1,bc:1,Rb:1,Hb:1,Ib:1,Sb:1,fa:1,Wb:1,wb:1,pa:1,Jb:1,Kb:1,Xb:1,kc:1,jc:1,nc:1,vb:1,lc:1,gc:1,tb:1,Ca:1,Ba:1,hc:1,Nb:1,Ob:1,ic:1,Nc:1,Qb:1,Fc:1,l:1,fc:1,cc:1,$b:1,z:1,d:1});function Ic(){this.A=null}Ic.prototype=new Hc;Ic.prototype.constructor=Ic;e=Ic.prototype;e.$=function(a){return this.A[a]};e.Q=function(a){return this.A[a|0]};e.S=function(a){La(this,a)};
e.ca=function(){return wc(this,this.A.length|0)};e.U=function(){return this.A.length|0};e.p=function(){return Nb(this)};function yb(a){var b=new Ic;b.A=a;return b}e.La=function(){return"WrappedArray"};e.a=y({oc:0},"scala.scalajs.js.WrappedArray",{oc:1,Oc:1,ec:1,Fb:1,Eb:1,Gb:1,c:1,Yb:1,Zb:1,dc:1,ac:1,Y:1,X:1,Mb:1,Vb:1,Lb:1,bc:1,Rb:1,Hb:1,Ib:1,Sb:1,fa:1,Wb:1,wb:1,pa:1,Jb:1,Kb:1,Xb:1,kc:1,jc:1,nc:1,vb:1,lc:1,gc:1,tb:1,Ca:1,Qc:1,Rc:1,cc:1,$b:1,Kc:1,Jc:1,Lc:1,hc:1,Nb:1,Ob:1,ic:1,Pc:1,Sc:1,Qb:1,fc:1});
Ra||(Ra=(new G).b());l.testScalaObj=Ra;l.spike=l.spike||{};l.spike.webapp=l.spike.webapp||{};l.spike.webapp.js=l.spike.webapp.js||{};l.spike.webapp.js.SpikeApp=function(){Cb||(Cb=(new Q).b());return Cb};
}).call(this);
//# sourceMappingURL=spike-opt.js.map
